kind: ConfigMap
apiVersion: v1
metadata:
  name: deployment-configmap
  namespace: default
data:
  # Please add values for labels that are in format "{...}" in this file. Other values should not be changed.

  # The connection string will be of format
  # "HostName={hubname}.azure-devices.net;SharedAccessKeyName={policy type};SharedAccessKey={Access Key};"
  # Policy Type can have following values: iothubowner, service, device, registryRead, registryReadWrite
  # The key will be shown in CLI window as output when remote-cli command has finished running.
  # Alternatively it can be accessed from http://portal.azure.com under {myResourceGroupName}
  # and resource type "Iot Hub" then "Shared access policies" menu.
  iothub.connstring: "{IoT Hub connection string}"

  # The connection string Document DB will be of format "AccountEndpoint={URI};AccountKey={Key};"
  # The key will be shown in CLI window as output when remote-cli command has finished running.
  # Alternatively it can be accessed from http://portal.azure.com under {myResourceGroupName}
  # and resource type "Azure Cosmos DB account" then "Keys" menu.
  docdb.connstring: "{DocumentDB connection string}"

  # Storage Adapter
  storageadapter.webservice.url: "http://storage-adapter-svc:9022/v1"
  storagadapter.collectionlink: "{Storage Adapter DocumentDB collection link}"

  # Stream Analytics
  iothubreact.hub.name: "{Iot Hub React name}"
  iothubreact.hub.endpoint: "{Iot Hub React endpoint}"
  iothubreact.hub.partitions: "{Iot Hub React partitions}"
  iothubreact.azureblob.account: "{Azure Blob account name}"
  iothubreact.azureblob.key: "{Azure Blob account key}"