apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui-config
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ui-config
    spec:
      containers:
      - name: ui-config-pod
        image: azureiotpcs/pcs-ui-config-dotnet:latest
        ports:
        - containerPort: 9005
        env:
        - name: PCS_UICONFIG_WEBSERVICE_PORT
          value: "9005"
        - name: PCS_STORAGEADAPTER_WEBSERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: storageadapter.webservice.url
        - name: PCS_DEVICESIMULATION_WEBSERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: devicesimulation.webservice.url
        - name: PCS_DEVICETELEMETRY_WEBSERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: devicetelemetry.webservice.url
        - name: PCS_IOTHUBMANAGER_WEBSERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: deployment-configmap
              key: iothubmanager.webservice.url
---
apiVersion: v1
kind: Service
metadata:
  name: ui-config-svc
  labels:
    app: ui-config
spec:
  type: NodePort
  ports:
  - port: 9005
  selector:
    app: ui-config