version: '2'

# TODO: remove APPLICATION_SECRET
services:
  reverseproxy:
    image: azureiotpcs/remote-monitoring-nginx:${PCS_DOCKER_TAG}
    networks:
      - default_net
    ports:
      - "80:10080"
      - "443:10443"
    depends_on:
      - webui
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - config
      - diagnostics
    volumes:
      - /app/certs:/app/certs:ro

  webui:
    image: azureiotpcs/pcs-remote-monitoring-webui:${PCS_DOCKER_TAG}
    networks:
      - default_net
    depends_on:
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - config
      - diagnostics
    volumes:
      - /app/webui-config.js:/app/build/webui-config.js:ro

  auth:
    image: azureiotpcs/pcs-auth-dotnet:${PCS_DOCKER_TAG}
    networks:
      - default_net
    environment:
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_AAD_ENDPOINT_URL
      - PCS_AAD_TENANT
      - PCS_AAD_APPSECRET
      - PCS_ARM_ENDPOINT_URL
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET
      - APPLICATION_SECRET

  iothubmanager:
    image: azureiotpcs/iothub-manager-java:${PCS_DOCKER_TAG}
    networks:
      - default_net
    depends_on:
      - auth
      - storageadapter
    environment:
      - PCS_AUTH_WEBSERVICE_URL=http://auth:9001/v1
      - PCS_IOTHUB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET
      - APPLICATION_SECRET

  devicesimulation:
    image: azureiotpcs/device-simulation-dotnet:DS-1.0.2
    networks:
      - default_net
    depends_on:
      - storageadapter
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET
      - APPLICATION_SECRET
    # How one could mount custom device models
    #volumes:
    #  - ./my-device-models:/app/data:ro

  telemetry:
    image: azureiotpcs/telemetry-java:${PCS_DOCKER_TAG}
    networks:
      - default_net
    depends_on:
      - auth
      - storageadapter
    environment:
      - PCS_AUTH_WEBSERVICE_URL=http://auth:9001/v1
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_DIAGNOSTICS_WEBSERVICE_URL=http://diagnostics:9006/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET
      - APPLICATION_SECRET
      - PCS_AAD_TENANT
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET
      - PCS_TELEMETRY_STORAGE_TYPE
      - PCS_TSI_FQDN
      - PCS_AZUREBLOB_CONNSTRING
      - PCS_ACTION_EVENTHUB_CONNSTRING
      - PCS_ACTION_EVENTHUB_NAME
      - PCS_LOGICAPP_ENDPOINT_URL
      - PCS_SOLUTION_WEBSITE_URL

  config:
    image: azureiotpcs/pcs-config-java:${PCS_DOCKER_TAG}
    networks:
      - default_net
    depends_on:
      - auth
      - storageadapter
      - devicesimulation
      - telemetry
    environment:
      - PCS_AUTH_WEBSERVICE_URL=http://auth:9001/v1
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_DEVICESIMULATION_WEBSERVICE_URL=http://devicesimulation:9003/v1
      - PCS_TELEMETRY_WEBSERVICE_URL=http://telemetry:9004/v1
      - PCS_SOLUTION_TYPE
      - PCS_AZUREMAPS_KEY
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET
      - APPLICATION_SECRET
      - PCS_SEED_TEMPLATE
      - PCS_ARM_ENDPOINT_URL
      - PCS_OFFICE365_CONNECTION_URL
      - PCS_SOLUTION_NAME
      - PCS_SUBSCRIPTION_ID

  storageadapter:
    image: azureiotpcs/pcs-storage-adapter-java:${PCS_DOCKER_TAG}
    networks:
      - default_net
    environment:
      - PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET
      - APPLICATION_SECRET

  asamanager:
    image: azureiotpcs/asa-manager-dotnet:${PCS_DOCKER_TAG}
    networks:
      - default_net
    depends_on:
      - iothubmanager
      - config
    environment:
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_TELEMETRY_WEBSERVICE_URL=http://telemetry:9004/v1
      - PCS_CONFIG_WEBSERVICE_URL=http://config:9005/v1
      - PCS_IOTHUBMANAGER_WEBSERVICE_URL=http://iothubmanager:9002/v1
      - PCS_ASA_DATA_AZUREBLOB_ACCOUNT
      - PCS_ASA_DATA_AZUREBLOB_KEY
      - PCS_ASA_DATA_AZUREBLOB_ENDPOINT_SUFFIX
      - PCS_EVENTHUB_CONNSTRING
      - PCS_EVENTHUB_NAME
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_APPLICATION_SECRET
      - PCS_TELEMETRY_STORAGE_TYPE

  diagnostics:
    image: azureiotpcs/pcs-diagnostics-dotnet:${PCS_DOCKER_TAG}
    networks:
      - default_net
    depends_on:
      - config
    environment:
      - PCS_LOG_LEVEL
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_CLOUD_TYPE
      - PCS_SUBSCRIPTION_ID
      - PCS_SOLUTION_TYPE
      - PCS_SOLUTION_NAME
      - PCS_DEPLOYMENT_ID
      - PCS_IOTHUB_NAME
      - PCS_DIAGNOSTICS_ENDPOINT_URL
      - PCS_CONFIG_WEBSERVICE_URL=http://config:9005/v1

networks:
  default_net:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.18.0.0/16
         gateway: 172.18.0.1
