version: '2'

# TODO: remove APPLICATION_SECRET
services:
  reverseproxy:
    image: azureiotpcs/remote-monitoring-nginx:${PCS_DOCKER_TAG}
    networks:
      - default_net
    ports:
      - "80:10080"
      - "443:10443"
    depends_on:
      - webui
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - config
      - diagnostics
    volumes:
      - /app/certs:/app/certs:ro

  webui:
    image: azureiotpcs/pcs-remote-monitoring-webui:${PCS_DOCKER_TAG}
    networks:
      - default_net
    depends_on:
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - config
      - diagnostics
    volumes:
      - /app/webui-config.js:/app/build/webui-config.js:ro

  auth:
    image: azureiotpcs/pcs-auth-dotnet:${PCS_DOCKER_TAG}
    networks:
      - default_net
    environment:
      - PCS_KEYVAULT_NAME

  iothubmanager:
    image: azureiotpcs/iothub-manager-java:${PCS_DOCKER_TAG}
    networks:
      - default_net
    depends_on:
      - auth
      - storageadapter
    environment:
      - PCS_KEYVAULT_NAME

  devicesimulation:
    image: azureiotpcs/device-simulation-dotnet:DS-1.0.4
    networks:
      - default_net
    restart: always
    depends_on:
      - storageadapter
    environment:
      - PCS_LOG_LEVEL
      - PCS_IOTHUB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_SUBSCRIPTION_ID
      - PCS_WEBUI_AUTH_AAD_APPID=${PCS_AAD_APPID}
      - PCS_WEBUI_AUTH_AAD_TENANT=${PCS_AAD_TENANT}
      - PCS_AAD_CLIENT_SP_ID=${PCS_AAD_APPID}
      - PCS_AAD_SECRET=${PCS_AAD_APPSECRET}
      - PCS_RESOURCE_GROUP=${PCS_SOLUTION_NAME}
      - PCS_IOHUB_NAME=${PCS_IOTHUB_NAME}
      - PCS_DIAGNOSTICS_WEBSERVICE_URL=http://diagnostics:9006/v1
      - PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING
      - PCS_AZURE_STORAGE_ACCOUNT=${PCS_AZUREBLOB_CONNSTRING}
      - PCS_SEED_TEMPLATE=remote-monitoring-simulations-template
      - PCS_SOLUTION_TYPE
    logging:
      driver: "json-file"
      options:
        max-size: "10240k"
        max-file: "10"
    volumes:
      - /tmp/share:/tmp/share

  telemetry:
    image: azureiotpcs/telemetry-java:${PCS_DOCKER_TAG}
    networks:
      - default_net
    depends_on:
      - auth
      - storageadapter
    environment:
      - PCS_KEYVAULT_NAME

  config:
    image: azureiotpcs/pcs-config-java:${PCS_DOCKER_TAG}
    networks:
      - default_net
    depends_on:
      - auth
      - storageadapter
      - devicesimulation
      - telemetry
    environment:
      - PCS_KEYVAULT_NAME

  storageadapter:
    image: azureiotpcs/pcs-storage-adapter-java:${PCS_DOCKER_TAG}
    networks:
      - default_net
    environment:
     - PCS_KEYVAULT_NAME

  asamanager:
    image: azureiotpcs/asa-manager-dotnet:${PCS_DOCKER_TAG}
    networks:
      - default_net
    depends_on:
      - iothubmanager
      - config
    environment:
      - PCS_KEYVAULT_NAME

  diagnostics:
    image: azureiotpcs/pcs-diagnostics-dotnet:Diagnostics-2.0.1
    networks:
      - default_net
    depends_on:
      - config
    environment:
      - PCS_KEYVAULT_NAME

networks:
  default_net:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.18.0.0/16
         gateway: 172.18.0.1
